### ISSUE TITLE
Code does not work 

### ISSUE THREAD

**Issue by waynelapierre** [returnandrisk/r-code#1]
fomcdatesrecent <- get.fomc.dates.recent()
[1] "Getting FOMC dates for recent years..."
Error in is.response(x) : Failure when receiving data from the peer
Called from: value[[3L]](cond)

**Comment by returnandrisk** [comment]
Unfortunately the Fed has once again changed the HTML format of their webpage and so my old code won't work now.
Also I don't use the code nor the dates now, so I won't be updating the code anymore.
However, a kind user manually updated the file recently and I have attached it for you.
[fomcdates_1936_2018.csv.zip](https://github.com/returnandrisk/r-code/files/2418426/fomcdates_1936_2018.csv.zip)
